apiVersion: v1
kind: Pod
metadata:
  name: pv-pod
spec:
  volumes:
  - name: pv-storage
    persistentVolumeClaim:
      claimName: pvc01
  containers:
  - name: box1
    image: busybox
    command:
    - sleep
    - "3600"
    volumeMounts:
    - mountPath: "/data"
      name: pv-storage
  - name: box2
    image: busybox
    command:
    - sleep
    - "3600"
    volumeMounts:
    - mountPath: "/data2"
      name: pv-storage
